services:
  db_postgres:
    image: postgres:15-alpine
    container_name: smarthome_db_postgres
    environment:
      POSTGRES_DB: smarthome
      POSTGRES_USER: smarthome_user
      POSTGRES_PASSWORD: smarthome_password
    ports:
      - "5432:5432"  # Проброс порта на хост (Windows)
    volumes:
      - ./db/init/init_postgres.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata_postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U smarthome_user -d smarthome"]
      interval: 5s
      timeout: 5s
      retries: 5
    profiles:
      - postgres

  db_mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: smarthome_db_mssql
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "StrongPass123!" # Придумайте сложный пароль
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P 'StrongPass123!' -Q 'SELECT 1' || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 10
    profiles:
      - mssql



volumes:
  pgdata_postgres:
  mssql_data: