#db.type=postgresql
db.type=sqlserver

# Настройки для удаленного Postgres
postgresql.driver=org.postgresql.Driver
postgresql.url=jdbc:postgresql://3e24e-rw.db.pub.dbaas.postgrespro.ru:5432/dbstud
postgresql.user=svistunova_va
postgresql.password=E$S54f7g%rOu

# Настройки для SQL Server
sqlserver.driver=com.microsoft.sqlserver.jdbc.SQLServerDriver
# Важно: trustServerCertificate=true нужен для самоподписанных сертификатов в Docker
sqlserver.url=jdbc:sqlserver://localhost:1433;databaseName=smarthome;encrypt=false;trustServerCertificate=true;
sqlserver.user=sa
sqlserver.password=StrongPass123!