#db.type=postgresql
db.type=sqlserver


postgresql.url=jdbc:postgresql://3e24e-rw.db.pub.dbaas.postgrespro.ru:5432/dbstud
postgresql.user=svistunova_va
postgresql.password=E$S54f7g%rOu
postgresql.driver=org.postgresql.Driver


sqlserver.url=jdbc:sqlserver://localhost:1433;databaseName=smarthome;encrypt=false;
sqlserver.user=sa
sqlserver.password=root
sqlserver.driver=com.microsoft.sqlserver.jdbc.SQLServerDriver